# =====================================================================
#  Project: Finja Musik Docker Spotify - Docker Compose
#  Module: finja-music-docker-spotify
#  Author: J. Apps (JohnV2002 / Sodakiller1)
#  Version: 1.0.1
#  Description: Docker Compose configuration for the Music API service.
#
#  ✨ New in 1.0.1:
#    • Updated port mapping to match Dockerfile (8022)
#    • Updated copyright to 2026
#
# ---------------------------------------------------------------------
#  Copyright (c) 2026 J. Apps
#  Licensed under the MIT License.
# =====================================================================

version: '3.8'

services:
  finja-musik-api:
    build: .
    container_name: finja-musik-api
    env_file:
      - .env
    ports:
      - "8022:8022"
    volumes:
      - ./Nowplaying:/app/Nowplaying
      - ./Memory:/app/Memory
      - ./SongsDB:/app/SongsDB
      - ./cache:/app/cache
      - ./config.json:/app/config.json
      - ./config_min.json:/app/config_min.json
    user: "${UID}:${GID}"
    restart: unless-stopped